version: 2
jobs:
  build:
      working_directory: ~/ng2-facebook-sdk/
      docker:
        - image: node:7
      branches:
        - only:
          - v2
      steps:
        - checkout
        - restore_cache:
           key: node_modules_{{ checksum "package.json" }}
        - run:
           name: Install node modules
           command: npm i
        - save_cache:
           key: node_modules_{{ checksum "package.json" }}
           paths:
             - ~/ng2-facebook-sdk/node_modules/
        - run:
           name: Build module
           command: npm run build
        - run:
           name: Build docs
           command: node scripts/update_docs.js
        - deploy:
           name: Deploy docs to gh-pages
           command: bash ./scripts/update_docs.sh
        - run: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "hello world"
            else
              echo "hello two worlds ${CIRCLE_BRANCH}"
            fi
